Perform a numerical analysis and data manipulation using the NumPy library

1.Creae a NumPy array

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


2.Access and manipulate elements in the array.

In [ ]:
arr1[2]

3

In [ ]:
arr1[2]=5
arr1

array([1, 2, 5])

3.Create a 2 dimensional array and check the shape of the array.

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
print("The shape is 2 rows and 3 columns",arr2.shape)

The shape is 2 rows and 3 columns (2, 3)


4.Access elements from the 2D array using index positions.

In [ ]:
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


5.Create an array of type string.

In [ ]:
arr3=np.array(["India","China","USA","Mexico"])
print(arr3)

['India' 'China' 'USA' 'Mexico']


6.Using the arange() and linspace() functions to evenly space values in a space.

In [ ]:
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


7.Create an array of random values between 0 and 1 ina given shape.

In [ ]:
arr1=np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


[[0.43831441 0.11471274 0.67161325 0.89424082]
 [0.03438653 0.01417469 0.70587121 0.33524663]
 [0.37490085 0.54913559 0.31862949 0.7832068 ]]


8.Create an array of constant values in a given shape.

In [ ]:
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


9.Repeat each element of an array by a specified number of times using repeat() a functions.

In [ ]:
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [ ]:
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


10.Create an identity matrix using eye() and identify() function.

In [ ]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11.Create a 5*5 2D array for random numbers between 0 and 1.

In [ ]:
arr=np.random.rand(5,5)
print(arr)

[[0.55950466 0.95169911 0.504175   0.6717437  0.63643551]
 [0.83012133 0.04445706 0.88767917 0.31262648 0.95531348]
 [0.03351667 0.81184527 0.00573932 0.79590716 0.61661004]
 [0.17194455 0.63488538 0.04751311 0.64045336 0.46161222]
 [0.512565   0.61041502 0.14628931 0.63328646 0.89863386]]


12.Sum and array along the column.

In [ ]:
print(np.sum(arr,axis=0))

[2.10765221 3.05330184 1.59139591 3.05401716 3.5686051 ]


13.Sum and array along the row.

In [ ]:
print(np.sum(arr,axis=1))

[3.32355798 3.03019754 2.26361844 1.95640861 2.80118966]


14.Calculate the mean,median,standard deviation,and variance.

In [ ]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.5349988891371773
0.6166100366658521
0.30069870641700025
0.0904197120408573


15.Sort an array along the row using the sort() function .

In [ ]:
arr=np.random.rand(5,5)
print(arr)

[[0.53712587 0.8284472  0.12859134 0.319228   0.20678005]
 [0.02204639 0.22418639 0.98233989 0.25345105 0.74939057]
 [0.73691645 0.07693732 0.11349674 0.45245714 0.55014427]
 [0.03705567 0.05814053 0.13666384 0.8065361  0.45598387]
 [0.68952569 0.92002674 0.23094568 0.72980672 0.51866744]]


In [ ]:
print(np.sort(arr,axis=1))

[[0.12859134 0.20678005 0.319228   0.53712587 0.8284472 ]
 [0.02204639 0.22418639 0.25345105 0.74939057 0.98233989]
 [0.07693732 0.11349674 0.45245714 0.55014427 0.73691645]
 [0.03705567 0.05814053 0.13666384 0.45598387 0.8065361 ]
 [0.23094568 0.51866744 0.68952569 0.72980672 0.92002674]]


16.Append elements to an array using the append() function.

In [ ]:
arr=np.array([4,5,6,7])
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [ ]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


17.Delete multiple elements in an array.

In [ ]:
arr2=np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


18.Concatenate elements from 2 arrays.

In [ ]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])

In [ ]:
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
